### PR TITLE
Simplify usage

### PR DESCRIPTION
**Pull request by jayvdb**
Fixing the README instructions to suit the package which hasnt been
published yet, and add hashbang and executable bit on entrypoint
script for local usage more suited to development.

### CODE REVIEW

**Comment by harmenjanssen** [comment]
I appreciate your contribution but this package is not at all production-ready.  
It even has my user_id hard-coded in it.

So I will leave this around for reference but I'm not sure when I'll be able to work on this project again.

**Comment by jayvdb** [comment]
It doesnt need to be production-ready -- and removing `user_id` is fairly easy.

I'm interested in getting JS devs working together on productive.io tools.
You might be interested in https://github.com/ilucin/productive-abuser/issues/1 .

**Comment by harmenjanssen** [comment]
Fair enough. 🙂 

I'm not that keen on the GUI version myself, that's why I started working on this lightweight CLI tool.
Next steps for me would be starting/stopping timers, and of course removing `user_id`, so everyone can log in.

Thanks for the interest, I'll see if I get around to this this week.

**Review by harmenjanssen — APPROVED** [review]
But your changes are actually fine. I'm going to merge this 👍

**Pull request merged**
